version: '3.8'

services:
  brassin-tracker:
    build: .
    ports:
      - "8502:8502"          # accessible sur http://ton-ip:8502
    volumes:
      - ./data:/data         # persistance de ta base SQLite
    restart: unless-stopped
