version: '3.8'

services:
  brassin-tracker:
    build: .
    ports:
      - "8501:8501"          # accessible sur http://ton-ip:8501
    volumes:
      - ./data:/data         # persistance de ta base SQLite
    restart: unless-stopped
